name: getx_clean_architecture
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  get: 4.6.6
  http: ^1.1.0
  intl: ^0.19.0
  phone_form_field: ^10.0.3
  url_launcher: 6.3.1
  url_launcher_ios: 6.3.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/news_icon.svg
    - assets/images/bg_image.svg
    - assets/images/register_screen_bg.svg
    - assets/images/register.svg
    - assets/icons/
    - assets/locales/
